-- ============================================================
-- VibeMarket: Seed 100 Best AI Tools (2026)
-- Run once in Supabase SQL Editor → https://supabase.com/dashboard
-- ============================================================

DO $$
DECLARE
BEGIN

  INSERT INTO public.tools
    (name, tagline, description, link, image_url, category, subcategory, tags,
     pricing_model, price, has_discount, discount_percentage, original_price,
     has_free_trial, free_trial_days, status, created_by)
  VALUES

  -- ─── AI / ML ───────────────────────────────────────────────────────────────
  ('Claude',
   'Anthropic''s flagship AI with advanced reasoning',
   'Claude is Anthropic''s AI assistant known for nuanced reasoning, coding, and long-context understanding. Available in multiple tiers including the powerful Claude 3.5 Sonnet and Opus models.',
   'https://claude.ai', 'https://logo.clearbit.com/claude.ai',
   'ai-ml', '', ARRAY['chatbot','reasoning','anthropic','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('ChatGPT',
   'OpenAI''s conversational AI used by 300M+ people',
   'The world''s most used AI assistant, capable of writing, coding, analysis, image generation, and reasoning across virtually any topic.',
   'https://chatgpt.com', 'https://logo.clearbit.com/openai.com',
   'ai-ml', '', ARRAY['chatbot','openai','gpt4','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Gemini',
   'Google''s multimodal AI integrated across all Google products',
   'Google''s most capable AI assistant, deeply integrated with Search, Gmail, Docs, and YouTube. Excels at long-context tasks with its 1M token window.',
   'https://gemini.google.com', 'https://logo.clearbit.com/google.com',
   'ai-ml', '', ARRAY['chatbot','google','multimodal','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Grok',
   'xAI''s witty AI with real-time web and X data access',
   'Grok is xAI''s AI assistant with a unique personality and real-time access to information on X (Twitter). Features strong reasoning with Grok 3 and DeepSearch capabilities.',
   'https://grok.com', 'https://logo.clearbit.com/x.ai',
   'ai-ml', '', ARRAY['chatbot','xai','real-time','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Microsoft Copilot',
   'AI assistant powered by GPT-4 built into Windows and Microsoft 365',
   'Microsoft''s AI assistant integrated across Windows, Edge, Office apps, and Teams. Powered by OpenAI''s latest models with enterprise-grade privacy.',
   'https://copilot.microsoft.com', 'https://logo.clearbit.com/microsoft.com',
   'ai-ml', '', ARRAY['chatbot','microsoft','office','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Perplexity AI',
   'AI search engine with real-time answers and cited sources',
   'Perplexity replaces traditional search with direct AI-powered answers backed by live web citations. Great for research, news, and deep dives on any topic.',
   'https://perplexity.ai', 'https://logo.clearbit.com/perplexity.ai',
   'ai-ml', '', ARRAY['search','research','real-time','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Meta AI',
   'Meta''s free AI assistant across WhatsApp, Instagram, and Messenger',
   'Meta AI is available for free across all Meta platforms. Powered by Llama models, it helps with everyday tasks, image generation, and creative projects.',
   'https://meta.ai', 'https://logo.clearbit.com/meta.com',
   'ai-ml', '', ARRAY['chatbot','meta','free','llama'],
   'free','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Mistral',
   'Fast, open-weight AI models from Europe''s leading AI lab',
   'Mistral AI offers state-of-the-art open-weight models including Mistral Large and Mixtral. Known for speed, efficiency, and transparency.',
   'https://chat.mistral.ai', 'https://logo.clearbit.com/mistral.ai',
   'ai-ml', '', ARRAY['chatbot','open-source','european','fast'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('DeepSeek',
   'High-performance open-source reasoning AI from China',
   'DeepSeek offers powerful open-weight models with exceptional reasoning and coding capabilities, often matching frontier models at a fraction of the cost.',
   'https://deepseek.com', 'https://logo.clearbit.com/deepseek.com',
   'ai-ml', '', ARRAY['chatbot','open-source','reasoning','coding'],
   'free','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Poe',
   'Multi-model platform to chat with Claude, GPT-4, and Gemini in one place',
   'Poe by Quora gives access to Claude, ChatGPT, Gemini, and dozens of other AI models in a single app. Great for comparing models and building custom bots.',
   'https://poe.com', 'https://logo.clearbit.com/poe.com',
   'ai-ml', '', ARRAY['chatbot','multi-model','quora','aggregator'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('HuggingChat',
   'Open-source AI chat powered by community models',
   'HuggingFace''s free chat interface running open-source models. No login required, transparent, and community-driven with access to the latest open models.',
   'https://huggingface.co/chat', 'https://logo.clearbit.com/huggingface.co',
   'ai-ml', '', ARRAY['chatbot','open-source','huggingface','free'],
   'free','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('You.com',
   'AI search engine with coding, writing, and research modes',
   'You.com combines AI chat with real-time web search and specialized modes for developers, writers, and researchers. Customizable with privacy-first design.',
   'https://you.com', 'https://logo.clearbit.com/you.com',
   'ai-ml', '', ARRAY['search','coding','privacy','multi-mode'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Cohere',
   'Enterprise AI APIs for search, generation, and classification',
   'Cohere provides production-grade language model APIs built for enterprise. Specializes in RAG, embeddings, and multilingual support for business applications.',
   'https://cohere.com', 'https://logo.clearbit.com/cohere.com',
   'ai-ml', '', ARRAY['api','enterprise','embeddings','rag'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Character.AI',
   'Create and chat with AI characters with unique personalities',
   'Character.AI lets you build and talk to custom AI personas from historical figures to fictional characters. Millions of community-created bots available.',
   'https://character.ai', 'https://logo.clearbit.com/character.ai',
   'ai-ml', '', ARRAY['chatbot','characters','creative','roleplay'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── DEV TOOLS ─────────────────────────────────────────────────────────────
  ('GitHub Copilot',
   'AI pair programmer from GitHub with code completion and chat',
   'GitHub Copilot is the world''s most widely adopted AI coding assistant. Integrates into VS Code, JetBrains, and Neovim with context-aware suggestions and a built-in chat agent.',
   'https://github.com/features/copilot', 'https://logo.clearbit.com/github.com',
   'dev-tools', '', ARRAY['coding','ide','microsoft','staff-pick'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Cursor',
   'The AI-first code editor built on VS Code',
   'Cursor is a VS Code fork redesigned for AI-assisted development. Features deep codebase understanding, agent mode, and multi-file edits that make it the #1 AI editor for professionals.',
   'https://cursor.com', 'https://logo.clearbit.com/cursor.com',
   'dev-tools', '', ARRAY['ide','coding','agent','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Windsurf',
   'AI-powered IDE with autonomous coding flows by Codeium',
   'Windsurf by Codeium introduces Cascade — an agentic AI that can plan, write, and debug entire features autonomously while keeping you in the loop.',
   'https://codeium.com/windsurf', 'https://logo.clearbit.com/codeium.com',
   'dev-tools', '', ARRAY['ide','coding','agent','autonomous'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Bolt.new',
   'Build and deploy full-stack apps in your browser with AI',
   'Bolt.new lets you build complete web applications from a prompt — right in your browser. No setup needed. Powered by StackBlitz with instant preview and one-click deployment.',
   'https://bolt.new', 'https://logo.clearbit.com/stackblitz.com',
   'dev-tools', '', ARRAY['no-code','fullstack','browser','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Lovable',
   'Ship production-ready web apps using natural language',
   'Lovable (formerly GPT Engineer) turns your ideas into working, deployable applications. Built for founders and makers who want to build fast without deep coding skills.',
   'https://lovable.dev', 'https://logo.clearbit.com/lovable.dev',
   'dev-tools', '', ARRAY['no-code','fullstack','founder','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('v0',
   'Vercel''s AI that generates React UI components from prompts',
   'v0 by Vercel generates production-quality React and shadcn/ui components from text descriptions or screenshots. The fastest way to go from idea to polished UI.',
   'https://v0.dev', 'https://logo.clearbit.com/vercel.com',
   'dev-tools', '', ARRAY['ui','react','frontend','vercel','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Replit',
   'Cloud coding environment with AI agent for building and deploying',
   'Replit combines a full cloud IDE with an AI agent that can build and deploy apps on command. Supports 50+ languages with instant hosting.',
   'https://replit.com', 'https://logo.clearbit.com/replit.com',
   'dev-tools', '', ARRAY['ide','cloud','agent','deploy'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Devin',
   'The world''s first fully autonomous AI software engineer',
   'Devin by Cognition AI can independently plan and execute complex engineering tasks — setting up environments, writing code, debugging, and deploying end-to-end.',
   'https://cognition.ai', 'https://logo.clearbit.com/cognition.ai',
   'dev-tools', '', ARRAY['autonomous','agent','engineering','devops'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Tabnine',
   'Privacy-focused AI code completion for enterprise teams',
   'Tabnine delivers AI code completions trained on your codebase with strict privacy guarantees. Trusted by Fortune 500 companies and compliant with enterprise security requirements.',
   'https://tabnine.com', 'https://logo.clearbit.com/tabnine.com',
   'dev-tools', '', ARRAY['coding','enterprise','privacy','autocomplete'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Amazon Q Developer',
   'AWS''s AI coding assistant for cloud and DevOps engineers',
   'Amazon Q Developer integrates AI coding assistance with deep AWS knowledge — helping with code completion, security scanning, cloud architecture, and infrastructure tasks.',
   'https://aws.amazon.com/q/developer', 'https://logo.clearbit.com/aws.amazon.com',
   'dev-tools', '', ARRAY['coding','aws','cloud','devops'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Continue',
   'Open-source AI code assistant plugin for VS Code and JetBrains',
   'Continue is the leading open-source AI coding assistant. Bring your own models (Claude, GPT-4, Ollama) and customize every part of the experience.',
   'https://continue.dev', 'https://logo.clearbit.com/continue.dev',
   'dev-tools', '', ARRAY['open-source','ide','plugin','byom'],
   'free','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Aider',
   'AI pair programmer that edits your local git repo via terminal',
   'Aider lets you pair program with LLMs directly in your terminal. Makes coordinated changes across multiple files while keeping a clean git history.',
   'https://aider.chat', 'https://logo.clearbit.com/aider.chat',
   'dev-tools', '', ARRAY['terminal','git','open-source','pair-programming'],
   'free','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Codeium',
   'Free AI code autocomplete for 70+ programming languages',
   'Codeium provides fast, free AI code completions and chat across every major IDE and 70+ languages. Used by over 1 million developers worldwide.',
   'https://codeium.com', 'https://logo.clearbit.com/codeium.com',
   'dev-tools', '', ARRAY['autocomplete','free','ide','multi-language'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Sourcegraph Cody',
   'AI coding assistant with full codebase context and search',
   'Cody by Sourcegraph understands your entire codebase through code search. Write, fix, and refactor code with AI that knows every file and dependency.',
   'https://sourcegraph.com/cody', 'https://logo.clearbit.com/sourcegraph.com',
   'dev-tools', '', ARRAY['coding','codebase','search','context'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Claude Code',
   'Anthropic''s agentic CLI tool for deep coding tasks',
   'Claude Code is Anthropic''s terminal-based coding agent. It can explore codebases, write and edit files, run commands, and execute multi-step engineering tasks autonomously.',
   'https://claude.ai/code', 'https://logo.clearbit.com/anthropic.com',
   'dev-tools', '', ARRAY['cli','agent','anthropic','terminal'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── DESIGN ────────────────────────────────────────────────────────────────
  ('Midjourney',
   'World-class AI image generation with stunning aesthetics',
   'Midjourney produces some of the most visually impressive AI-generated images available. Operate via Discord or the web app to create art, concepts, and photorealistic visuals.',
   'https://midjourney.com', 'https://logo.clearbit.com/midjourney.com',
   'design', '', ARRAY['image-gen','art','creative','staff-pick'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('DALL-E 3',
   'OpenAI''s image generation integrated directly into ChatGPT',
   'DALL-E 3 sets the standard for prompt-following in image generation. Accessible through ChatGPT Plus or the OpenAI API for building visual applications.',
   'https://openai.com/dall-e-3', 'https://logo.clearbit.com/openai.com',
   'design', '', ARRAY['image-gen','openai','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Adobe Firefly',
   'Adobe''s generative AI for images, vectors, and video',
   'Firefly is Adobe''s commercially safe generative AI. Create images, enhance photos, generate vectors, and produce video clips — all trained on licensed content.',
   'https://firefly.adobe.com', 'https://logo.clearbit.com/adobe.com',
   'design', '', ARRAY['image-gen','adobe','vectors','commercial'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Ideogram',
   'AI image generator with best-in-class text rendering',
   'Ideogram excels at generating images with accurate text and typography — a major weakness of other AI image tools. Perfect for posters, logos, and branded visuals.',
   'https://ideogram.ai', 'https://logo.clearbit.com/ideogram.ai',
   'design', '', ARRAY['image-gen','typography','text','branding'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Leonardo AI',
   'AI image and asset generation for games and creative projects',
   'Leonardo AI offers high-quality image generation with fine-tuned models for game assets, concept art, and product imagery. Features a robust workflow editor.',
   'https://leonardo.ai', 'https://logo.clearbit.com/leonardo.ai',
   'design', '', ARRAY['image-gen','game-assets','concept-art','creative'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Recraft',
   'AI vector art and image generation built for professional designers',
   'Recraft generates brand-consistent images, icons, and vectors in custom styles. The only AI image tool with true SVG output and full brand style control.',
   'https://recraft.ai', 'https://logo.clearbit.com/recraft.ai',
   'design', '', ARRAY['image-gen','vector','svg','branding'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Runway ML',
   'Professional AI video generation and editing platform',
   'Runway is a leading AI creative suite for video generation, inpainting, motion tracking, and real-time video effects. Used by Hollywood studios and indie creators.',
   'https://runwayml.com', 'https://logo.clearbit.com/runwayml.com',
   'design', '', ARRAY['video-gen','creative','film','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Sora',
   'OpenAI''s cinematic text-to-video generation model',
   'Sora generates stunning, realistic video clips up to 20 seconds from text prompts or images. Capable of complex camera movements, lighting, and physics simulation.',
   'https://sora.com', 'https://logo.clearbit.com/openai.com',
   'design', '', ARRAY['video-gen','openai','cinematic','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Pika Labs',
   'Fast AI video generation from text, images, and existing clips',
   'Pika creates short video clips from text and images with expressive motion controls. Features include lip sync, sound effects, and style transformation.',
   'https://pika.art', 'https://logo.clearbit.com/pika.art',
   'design', '', ARRAY['video-gen','animation','lipsync'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Kling AI',
   'High-resolution AI video generation with realistic motion',
   'Kling AI by Kuaishou produces high-quality video generation with realistic physics, facial expressions, and motion. Strong at human movement and product showcases.',
   'https://klingai.com', 'https://logo.clearbit.com/klingai.com',
   'design', '', ARRAY['video-gen','realistic','chinese','motion'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('HeyGen',
   'AI video platform with photorealistic avatars for marketing',
   'HeyGen creates professional video content with AI avatars. Record once in any language, then translate and localize to 40+ languages with voice cloning and lip sync.',
   'https://heygen.com', 'https://logo.clearbit.com/heygen.com',
   'design', '', ARRAY['video-gen','avatars','localization','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Synthesia',
   'Create professional AI video presentations with digital avatars',
   'Synthesia turns scripts into polished video presentations with AI avatars at enterprise scale. No camera or editing skills needed — just type and publish.',
   'https://synthesia.io', 'https://logo.clearbit.com/synthesia.io',
   'design', '', ARRAY['video-gen','avatars','presentations','enterprise'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Luma Dream Machine',
   'Generate cinematic video clips from text or image prompts',
   'Luma AI''s Dream Machine creates high-quality 5-second video clips with stunning visual fidelity. Particularly strong for product shots and fantasy scenes.',
   'https://lumalabs.ai', 'https://logo.clearbit.com/lumalabs.ai',
   'design', '', ARRAY['video-gen','3d','product','cinematic'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Canva AI',
   'Design platform with Magic Studio AI for images and video',
   'Canva''s AI suite (Magic Studio) includes text-to-image, background removal, video generation, and AI presentations — all inside the world''s most popular design tool.',
   'https://canva.com', 'https://logo.clearbit.com/canva.com',
   'design', '', ARRAY['design','image-gen','presentations','templates'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Figma AI',
   'Design and prototype faster with AI-powered suggestions',
   'Figma AI adds generative design, auto-layout suggestions, asset search, and AI wireframing directly into the world''s leading collaborative design tool.',
   'https://figma.com', 'https://logo.clearbit.com/figma.com',
   'design', '', ARRAY['design','prototyping','ui','collaboration'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── MEDIA ─────────────────────────────────────────────────────────────────
  ('ElevenLabs',
   'Ultra-realistic AI voice cloning and text-to-speech',
   'ElevenLabs produces the most natural-sounding AI voices available. Clone any voice in seconds, generate speech in 32 languages, and build voice agents for any app.',
   'https://elevenlabs.io', 'https://logo.clearbit.com/elevenlabs.io',
   'media', '', ARRAY['voice','tts','cloning','speech','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Suno AI',
   'Generate full radio-quality songs with vocals from a text prompt',
   'Suno turns a brief text description into a complete song with instruments, vocals, and lyrics in any musical genre — in under 30 seconds.',
   'https://suno.com', 'https://logo.clearbit.com/suno.com',
   'media', '', ARRAY['music-gen','vocals','lyrics','creative'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Udio',
   'Create original music in any genre using AI',
   'Udio generates high-quality original music with vocals and instruments from simple text descriptions. Strong on genre accuracy and production polish.',
   'https://udio.com', 'https://logo.clearbit.com/udio.com',
   'media', '', ARRAY['music-gen','vocals','creative','audio'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Mubert',
   'Generate royalty-free background music for content creators',
   'Mubert uses AI to generate custom, royalty-free music tracks for videos, podcasts, and apps. Specify mood, genre, and duration to get the perfect soundtrack.',
   'https://mubert.com', 'https://logo.clearbit.com/mubert.com',
   'media', '', ARRAY['music-gen','royalty-free','background-music','api'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Descript',
   'AI video and podcast editor with transcript-based editing',
   'Descript lets you edit video and audio like a text document. Cut, remove filler words, overdub your voice, and publish in one seamless workflow.',
   'https://descript.com', 'https://logo.clearbit.com/descript.com',
   'media', '', ARRAY['video-editing','podcast','transcription','overdub'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Adobe Podcast',
   'AI-powered audio recording and enhancement for podcasters',
   'Adobe Podcast''s Enhance Speech feature removes background noise and improves recording quality to studio level — even from laptop microphones.',
   'https://podcast.adobe.com', 'https://logo.clearbit.com/adobe.com',
   'media', '', ARRAY['podcast','audio-enhancement','noise-removal','adobe'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Speechify',
   'Turn any text, PDF, or document into audio with AI voices',
   'Speechify converts any written content — emails, articles, PDFs, textbooks — into natural audio you can listen to at up to 4.5x speed.',
   'https://speechify.com', 'https://logo.clearbit.com/speechify.com',
   'media', '', ARRAY['tts','reading','productivity','accessibility'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('AIVA',
   'AI music composition for films, games, and advertisements',
   'AIVA (Artificial Intelligence Virtual Artist) composes emotional soundtracks and background music for any creative project. Used by professionals in film and game scoring.',
   'https://aiva.ai', 'https://logo.clearbit.com/aiva.ai',
   'media', '', ARRAY['music-gen','composition','film','games'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── PRODUCTIVITY ──────────────────────────────────────────────────────────
  ('Notion AI',
   'AI writing, summarizing, and organizing inside your Notion workspace',
   'Notion AI is built into every page in Notion. Write faster, summarize meeting notes, translate content, and auto-fill databases without leaving your workspace.',
   'https://notion.so', 'https://logo.clearbit.com/notion.so',
   'productivity', '', ARRAY['writing','notes','organization','workspace','staff-pick'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Grammarly AI',
   'Advanced AI writing assistant for grammar, tone, and clarity',
   'Grammarly checks grammar, spelling, tone, and style in real-time across every app you use. The AI features now rewrite, generate, and personalize text for any context.',
   'https://grammarly.com', 'https://logo.clearbit.com/grammarly.com',
   'productivity', '', ARRAY['writing','grammar','tone','browser-extension'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Jasper AI',
   'AI content creation platform for marketing teams',
   'Jasper helps marketing teams create on-brand content at scale. Trained on your brand voice and integrated with SEO tools for blog posts, social content, and ad copy.',
   'https://jasper.ai', 'https://logo.clearbit.com/jasper.ai',
   'productivity', '', ARRAY['writing','marketing','brand','content'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Copy.ai',
   'AI copywriting for ads, emails, and sales sequences',
   'Copy.ai generates high-converting marketing copy, cold emails, and social posts in seconds. Features powerful workflows for sales and GTM teams.',
   'https://copy.ai', 'https://logo.clearbit.com/copy.ai',
   'productivity', '', ARRAY['copywriting','marketing','sales','emails'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Writesonic',
   'AI writing platform for content, SEO, and chatbots',
   'Writesonic covers blog posts, landing pages, and ad copy with real-time web data. Includes Chatsonic (AI search) and Botsonic (custom chatbot builder).',
   'https://writesonic.com', 'https://logo.clearbit.com/writesonic.com',
   'productivity', '', ARRAY['writing','seo','chatbot','content'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Otter.ai',
   'Real-time AI meeting transcription, summaries, and action items',
   'Otter.ai joins your Zoom, Teams, and Google Meet calls to transcribe, summarize, and extract action items automatically. Integrates with Salesforce and Notion.',
   'https://otter.ai', 'https://logo.clearbit.com/otter.ai',
   'productivity', '', ARRAY['meetings','transcription','notes','summaries'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Fireflies.ai',
   'AI notetaker that records, transcribes, and analyzes your meetings',
   'Fireflies records and transcribes meetings across every platform, then uses AI to surface insights, track topics, and push action items to your CRM.',
   'https://fireflies.ai', 'https://logo.clearbit.com/fireflies.ai',
   'productivity', '', ARRAY['meetings','transcription','crm','insights'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Grain',
   'AI meeting recorder with coaching insights and highlights',
   'Grain clips and highlights the most important moments from sales and customer calls. Used by revenue teams to coach reps and capture customer feedback.',
   'https://grain.com', 'https://logo.clearbit.com/grain.com',
   'productivity', '', ARRAY['meetings','sales','coaching','highlights'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Loom AI',
   'Video messaging with automatic AI summaries and chapters',
   'Loom lets you record and share video messages instantly. AI automatically adds titles, summaries, chapters, and task lists to every recording.',
   'https://loom.com', 'https://logo.clearbit.com/loom.com',
   'productivity', '', ARRAY['video','async','meetings','summaries'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Gamma',
   'Create polished presentations and documents from AI prompts',
   'Gamma turns ideas into beautiful presentations, docs, and web pages in one click. No slide-by-slide formatting — just describe and publish.',
   'https://gamma.app', 'https://logo.clearbit.com/gamma.app',
   'productivity', '', ARRAY['presentations','docs','design','ai-powered'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Framer AI',
   'Build and publish websites from plain text descriptions',
   'Framer AI generates complete, interactive websites from text prompts. Combine with Framer''s powerful visual editor for professional-grade results.',
   'https://framer.com', 'https://logo.clearbit.com/framer.com',
   'productivity', '', ARRAY['website','no-code','design','landing-page'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Superdesign',
   'AI-powered design platform for creating beautiful interfaces',
   'Superdesign uses AI to help you create stunning UI components, landing pages, and design systems. Generate production-ready designs from prompts.',
   'https://superdesign.dev', 'https://logo.clearbit.com/superdesign.dev',
   'productivity', '', ARRAY['design','ui','components','ai-powered'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── AUTOMATION ────────────────────────────────────────────────────────────
  ('Zapier AI',
   'Automate workflows between 7,000+ apps with natural language',
   'Zapier''s AI lets you build automation workflows by describing them in plain English. Connect your entire stack and add AI steps like summarization and classification.',
   'https://zapier.com', 'https://logo.clearbit.com/zapier.com',
   'automation', '', ARRAY['workflow','automation','integrations','no-code'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Make',
   'Visual workflow automation with powerful AI scenario building',
   'Make (formerly Integromat) is a visual automation platform for complex multi-step workflows. Offers advanced logic, data transformation, and AI module integrations.',
   'https://make.com', 'https://logo.clearbit.com/make.com',
   'automation', '', ARRAY['workflow','automation','visual','integrations'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('n8n',
   'Open-source workflow automation with AI nodes and self-hosting',
   'n8n is the open-source alternative to Zapier with code-level power. Self-hostable, AI-native, and extensible with 400+ integrations and custom logic.',
   'https://n8n.io', 'https://logo.clearbit.com/n8n.io',
   'automation', '', ARRAY['open-source','self-hosted','workflow','automation'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Lindy AI',
   'Build AI agents that handle email, scheduling, and CRM tasks',
   'Lindy creates AI employees that run autonomously — answering emails, booking meetings, updating your CRM, and triaging support tickets without supervision.',
   'https://lindy.ai', 'https://logo.clearbit.com/lindy.ai',
   'automation', '', ARRAY['ai-agent','email','crm','scheduling'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Bardeen',
   'AI automation for web scraping and repetitive browser tasks',
   'Bardeen automates manual web tasks directly in your browser. Extract data from any website, sync across tools, and trigger workflows without code.',
   'https://bardeen.ai', 'https://logo.clearbit.com/bardeen.ai',
   'automation', '', ARRAY['browser','scraping','workflow','no-code'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Relevance AI',
   'Build, deploy, and scale AI agents and multi-agent teams',
   'Relevance AI is the platform for building custom AI agents that can use tools, browse the web, write code, and collaborate in multi-agent pipelines.',
   'https://relevanceai.com', 'https://logo.clearbit.com/relevanceai.com',
   'automation', '', ARRAY['ai-agent','multi-agent','tools','enterprise'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Clay',
   'AI-powered GTM data enrichment and personalized outreach',
   'Clay enriches leads with data from 100+ sources and uses AI to write hyper-personalized outreach at scale. The secret weapon of the best GTM teams.',
   'https://clay.com', 'https://logo.clearbit.com/clay.com',
   'automation', '', ARRAY['sales','enrichment','outreach','gtm'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Dust',
   'Build custom AI assistants and agents for your internal team',
   'Dust connects to your company''s Notion, Slack, GitHub, and Google Drive to build AI assistants that know your business context inside and out.',
   'https://dust.tt', 'https://logo.clearbit.com/dust.tt',
   'automation', '', ARRAY['ai-agent','internal','knowledge-base','team'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── MARKETING ─────────────────────────────────────────────────────────────
  ('AdCreative.ai',
   'Generate high-converting ad creatives and copy using AI',
   'AdCreative.ai produces hundreds of performance-optimized ad visuals and copy variations in minutes. Integrates with Google, Facebook, and DALL-E for full creative suites.',
   'https://adcreative.ai', 'https://logo.clearbit.com/adcreative.ai',
   'marketing', '', ARRAY['ads','creative','performance','facebook'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Predis.ai',
   'AI social media content creation with competitor analysis',
   'Predis turns a single idea into social posts, carousels, reels, and ad creatives for every platform — with built-in competitor analysis and a content calendar.',
   'https://predis.ai', 'https://logo.clearbit.com/predis.ai',
   'marketing', '', ARRAY['social-media','content','ads','calendar'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Surfer SEO',
   'AI-powered SEO content optimization and keyword planning',
   'Surfer analyzes top-ranking pages and tells you exactly how to write content that ranks. Includes keyword research, content editor, and AI writing integration.',
   'https://surferseo.com', 'https://logo.clearbit.com/surferseo.com',
   'marketing', '', ARRAY['seo','content','keywords','ranking'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Frase',
   'AI content briefs and SEO optimization for writers',
   'Frase researches any topic, builds comprehensive content briefs, and scores your drafts against top competitors in real-time. Pairs well with any AI writer.',
   'https://frase.io', 'https://logo.clearbit.com/frase.io',
   'marketing', '', ARRAY['seo','content-brief','writing','research'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Instantly AI',
   'AI cold email outreach platform with deliverability optimization',
   'Instantly manages unlimited sending accounts, rotates domains, and uses AI to personalize cold emails at scale — while keeping deliverability metrics green.',
   'https://instantly.ai', 'https://logo.clearbit.com/instantly.ai',
   'marketing', '', ARRAY['cold-email','outreach','sales','deliverability'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Smartly',
   'AI-powered social advertising automation at scale',
   'Smartly automates creative production and media buying across Facebook, TikTok, Snapchat, and Pinterest. Used by top e-commerce brands to scale ad performance.',
   'https://smartly.io', 'https://logo.clearbit.com/smartly.io',
   'marketing', '', ARRAY['ads','social','automation','enterprise'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Mutiny',
   'AI website personalization platform for B2B revenue growth',
   'Mutiny personalizes your website for every visitor segment without engineering work. B2B companies use it to convert pipeline faster with targeted messaging.',
   'https://mutinyhq.com', 'https://logo.clearbit.com/mutinyhq.com',
   'marketing', '', ARRAY['personalization','b2b','website','conversion'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Pencil AI',
   'AI ad creative generation with performance prediction',
   'Pencil generates video and static ad creatives for Facebook and TikTok, then predicts which will perform best before you spend a dollar on them.',
   'https://trypencil.com', 'https://logo.clearbit.com/trypencil.com',
   'marketing', '', ARRAY['ads','video','prediction','facebook'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  -- ─── EDUCATION ─────────────────────────────────────────────────────────────
  ('Khanmigo',
   'Socratic AI tutor for students and educators by Khan Academy',
   'Khanmigo is Khan Academy''s AI tutor powered by GPT-4. It guides students to answers through questions rather than giving them away, building genuine understanding.',
   'https://khanacademy.org/khan-labs', 'https://logo.clearbit.com/khanacademy.org',
   'education', '', ARRAY['tutoring','k12','math','learning'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Duolingo AI',
   'AI-powered language learning with personalized adaptive paths',
   'Duolingo uses AI to personalize lesson difficulty, provide conversational practice with AI characters, and adapt to your learning pace across 40+ languages.',
   'https://duolingo.com', 'https://logo.clearbit.com/duolingo.com',
   'education', '', ARRAY['language-learning','adaptive','gamified','mobile'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Coursera Coach',
   'AI learning coach providing personalized career skill guidance',
   'Coursera''s AI coach helps you choose courses, track progress, and get personalized explanations from industry-leading university and company courses.',
   'https://coursera.org', 'https://logo.clearbit.com/coursera.org',
   'education', '', ARRAY['online-learning','career','university','certificates'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Elicit',
   'AI research assistant for finding and analyzing scientific papers',
   'Elicit searches through millions of academic papers and extracts key findings, methodologies, and conclusions using AI. Essential for researchers and PhD students.',
   'https://elicit.com', 'https://logo.clearbit.com/elicit.com',
   'education', '', ARRAY['research','academic','papers','science'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Consensus',
   'AI-powered search engine for scientific research',
   'Consensus finds scientific consensus on any question by analyzing thousands of peer-reviewed studies. Get evidence-based answers with citations in seconds.',
   'https://consensus.app', 'https://logo.clearbit.com/consensus.app',
   'education', '', ARRAY['research','science','evidence','academic'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Wisdolia',
   'AI flashcard generator from any textbook, PDF, or document',
   'Wisdolia instantly creates spaced-repetition flashcards from any uploaded content. Students use it to turn lectures, textbooks, and notes into study sets.',
   'https://wisdolia.com', 'https://logo.clearbit.com/wisdolia.com',
   'education', '', ARRAY['flashcards','studying','spaced-repetition','students'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── COMMUNICATION ─────────────────────────────────────────────────────────
  ('Intercom Fin',
   'AI customer support agent that resolves 50%+ of tickets instantly',
   'Fin is Intercom''s AI agent trained on your support content. It handles repetitive tickets autonomously, escalates complex issues to humans, and learns continuously.',
   'https://intercom.com', 'https://logo.clearbit.com/intercom.com',
   'communication', '', ARRAY['customer-support','chatbot','helpdesk','enterprise'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Tidio',
   'AI chatbot for customer service and lead generation',
   'Tidio''s Lyro AI resolves up to 70% of customer inquiries automatically. Easy to set up, affordable, and works across live chat, email, and Messenger.',
   'https://tidio.com', 'https://logo.clearbit.com/tidio.com',
   'communication', '', ARRAY['chatbot','customer-support','live-chat','ecommerce'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Zoom AI Companion',
   'AI assistant for meeting summaries and smart scheduling in Zoom',
   'Zoom AI Companion summarizes meetings, drafts chat replies, creates action items, and helps compose emails — all without leaving the Zoom platform.',
   'https://zoom.us', 'https://logo.clearbit.com/zoom.us',
   'communication', '', ARRAY['meetings','summaries','scheduling','video'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Slack AI',
   'AI-powered search, summaries, and writing assistance in Slack',
   'Slack AI catches you up on missed conversations, answers questions from your channel history, and drafts messages — without leaving Slack.',
   'https://slack.com', 'https://logo.clearbit.com/slack.com',
   'communication', '', ARRAY['messaging','summaries','search','enterprise'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Drift',
   'AI-powered conversational marketing and B2B sales platform',
   'Drift uses AI to engage website visitors in real-time, qualify leads, and book meetings with sales reps automatically. A pioneer in conversational marketing.',
   'https://drift.com', 'https://logo.clearbit.com/drift.com',
   'communication', '', ARRAY['chatbot','b2b','sales','lead-gen'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Typeface',
   'Enterprise AI for brand-consistent content at scale',
   'Typeface trains on your brand guidelines, tone of voice, and visual assets to generate on-brand content across every channel — safely within enterprise controls.',
   'https://typeface.app', 'https://logo.clearbit.com/typeface.app',
   'communication', '', ARRAY['content','enterprise','brand','marketing'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  -- ─── FINANCE ───────────────────────────────────────────────────────────────
  ('Julius AI',
   'AI data analyst for financial charts, spreadsheets, and insights',
   'Julius AI analyzes spreadsheets, CSVs, and databases using natural language. Ask questions, generate charts, and run complex financial models without writing code.',
   'https://julius.ai', 'https://logo.clearbit.com/julius.ai',
   'finance', '', ARRAY['data-analysis','spreadsheets','charts','finance'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Akkio',
   'No-code AI platform for business analytics and forecasting',
   'Akkio lets non-technical teams build predictive AI models from their CRM and spreadsheet data. Forecast revenue, churn, and lead scoring without a data scientist.',
   'https://akkio.com', 'https://logo.clearbit.com/akkio.com',
   'finance', '', ARRAY['no-code','predictive-ai','analytics','crm'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Polygon AI',
   'Real-time financial market data APIs with AI analytics',
   'Polygon.io provides institutional-grade stock, options, forex, and crypto data APIs with AI-powered analytics tools for quants, traders, and fintech builders.',
   'https://polygon.io', 'https://logo.clearbit.com/polygon.io',
   'finance', '', ARRAY['api','stocks','crypto','market-data'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Upmetrics',
   'AI business plan writer with financial projection modeling',
   'Upmetrics generates complete business plans, pitch decks, and financial projections using AI. Trusted by 110,000+ entrepreneurs and startup founders.',
   'https://upmetrics.co', 'https://logo.clearbit.com/upmetrics.co',
   'finance', '', ARRAY['business-plan','startups','projections','pitch-deck'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  -- ─── SECURITY ──────────────────────────────────────────────────────────────
  ('Darktrace',
   'Self-learning AI cybersecurity with autonomous threat response',
   'Darktrace''s AI learns the normal behavior of every user and device on your network, then autonomously responds to threats in real-time — even zero-day attacks.',
   'https://darktrace.com', 'https://logo.clearbit.com/darktrace.com',
   'security', '', ARRAY['cybersecurity','threat-detection','autonomous','enterprise'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('SentinelOne',
   'AI-powered endpoint protection with real-time threat response',
   'SentinelOne''s Purple AI delivers autonomous endpoint, cloud, and identity security. It detects and neutralizes ransomware, malware, and supply chain attacks in milliseconds.',
   'https://sentinelone.com', 'https://logo.clearbit.com/sentinelone.com',
   'security', '', ARRAY['endpoint','antivirus','autonomous','enterprise'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com'),

  ('Snyk',
   'AI-powered developer security for code, containers, and dependencies',
   'Snyk finds and fixes security vulnerabilities in your code, open-source libraries, container images, and infrastructure-as-code — directly in the developer workflow.',
   'https://snyk.io', 'https://logo.clearbit.com/snyk.io',
   'security', '', ARRAY['devsec','vulnerabilities','open-source','devops'],
   'freemium','',false,'','',true,'','approved','k.ygs@icloud.com'),

  ('Abnormal Security',
   'AI email security protecting against phishing and BEC attacks',
   'Abnormal AI understands normal email behavior for every employee, then detects and blocks advanced phishing, business email compromise, and account takeover attacks.',
   'https://abnormalsecurity.com', 'https://logo.clearbit.com/abnormalsecurity.com',
   'security', '', ARRAY['email-security','phishing','bec','enterprise'],
   'subscription','',false,'','',false,'','approved','k.ygs@icloud.com');

END $$;
